// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TSwBPfCs-h1I_QxoK350SrEbUs2eSO0',
    appId: '1:716358193523:web:ce13ed840b050ee54ab506',
    messagingSenderId: '716358193523',
    projectId: 'chat-app-5f0f3',
    authDomain: 'chat-app-5f0f3.firebaseapp.com',
    storageBucket: 'chat-app-5f0f3.appspot.com',
    measurementId: 'G-P7XR52SRDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6k_ej785uW2kGmQtCcM8lefUT69maSs',
    appId: '1:716358193523:android:ef9ed4f896818b9b4ab506',
    messagingSenderId: '716358193523',
    projectId: 'chat-app-5f0f3',
    storageBucket: 'chat-app-5f0f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOMg5N2oVE2E-61vDITOuTL4EnrgdkQfY',
    appId: '1:716358193523:ios:43166122f01bfed34ab506',
    messagingSenderId: '716358193523',
    projectId: 'chat-app-5f0f3',
    storageBucket: 'chat-app-5f0f3.appspot.com',
    iosClientId: '716358193523-d8qcoiippmacvqep1lfl79lp3h6no56m.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatApp',
  );
}
